import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { ArrowLeft, CheckCircle2, MapPin, ShieldAlert, Ruler, Waves } from "lucide-react";
import { getDetection, updateDetectionStatus, verifyDetection } from "../services/detectionApi";
import Loading from "../components/common/Loading";
import RiskBadge from "../components/detection/RiskBadge";
import { formatNumber } from "../utils/format";

export default function DetectionDetails() {
  const {detectionId}=useParams(); const [d,setD]=useState(null),[error,setError]=useState(""),[image,setImage]=useState(null),[busy,setBusy]=useState(false);
  const load=()=>getDetection(detectionId).then(r=>setD(r.data.data)).catch(e=>setError(e.userMessage||"Could not load detection")); useEffect(load,[]);
  async function status(s){await updateDetectionStatus(detectionId,s);load()}
  async function verify(){setBusy(true);try{await verifyDetection(detectionId,image);load()}catch(e){setError(e.userMessage||"Verification failed")}finally{setBusy(false)}}
  if(!d&&!error)return <Loading/>; if(error)return <div className="rounded-xl border border-rose-400/20 bg-rose-400/10 p-4 text-rose-300">{error}</div>;
  const loc=d.location||{}, dim=d.dimensions||{}, shadow=d.shadowAnalysis||{}, pers=d.persistence||{};
  return <div className="space-y-6"><Link to="/map" className="flex items-center gap-2 text-sm text-slate-500"><ArrowLeft size={16}/>Back to map</Link><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs uppercase tracking-widest text-cyan-300">{d.detectionId}</p><h1 className="mt-1 text-3xl font-semibold capitalize">{d.classification?.replaceAll("_"," ")}</h1></div><RiskBadge risk={d.riskLevel}/></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Confidence",`${formatNumber(d.confidence)}%`,ShieldAlert],["Hazard",`${formatNumber(d.hazardScore)} / 100`,ShieldAlert],["Shadow",`${formatNumber(shadow.score)}%`,Waves],["Persistence",`${formatNumber(pers.persistenceScore)}%`,CheckCircle2]].map(([a,b,I])=><div key={a} className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><I className="text-cyan-300" size={19}/><p className="mt-4 text-xs text-slate-500">{a}</p><p className="mt-1 text-2xl font-semibold">{b}</p></div>)}</div>
    <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><h2 className="font-semibold">AI analysis</h2><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><Info label="Artificial probability" value={`${formatNumber(d.artificialProbability)}%`}/><Info label="Natural probability" value={`${formatNumber(d.naturalProbability)}%`}/><Info label="Shadow length" value={`${formatNumber(shadow.lengthPixels)} px`}/><Info label="Frames seen" value={pers.framesSeen??"—"}/></div><div className="mt-5 rounded-xl bg-cyan-400/[.04] p-4 text-sm text-slate-300"><div className="font-medium text-cyan-200">Evidence signals</div><ul className="mt-3 space-y-2 text-slate-400"><li>✓ Model confidence contributes to final score</li><li>✓ Acoustic shadow analysis: {shadow.detected?"detected":"not detected"}</li><li>✓ Artificial probability: {formatNumber(d.artificialProbability)}%</li><li>✓ Multi-frame confirmation: {pers.confirmed?"confirmed":"not confirmed"}</li></ul></div></section>
    <section className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><h2 className="font-semibold">Location & dimensions</h2><div className="mt-5 space-y-4"><Info icon={MapPin} label="Coordinates" value={loc.available?`${loc.latitude}, ${loc.longitude}`:"Unavailable"}/><Info icon={Ruler} label="Dimensions" value={dim.available?`${formatNumber(dim.lengthM)} m × ${formatNumber(dim.widthM)} m`:"Unavailable"}/><Info label="Area" value={dim.available?`${formatNumber(dim.areaM2)} m²`:"Unavailable"}/><Info label="Depth" value={loc.available?`${formatNumber(loc.depthM)} m`:"Unavailable"}/></div></section></div>
    <section className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><h2 className="font-semibold">Verification</h2><p className="mt-1 text-xs text-slate-500">Use an underwater camera image when the AI recommends verification.</p><div className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-center"><input type="file" accept="image/*" onChange={e=>setImage(e.target.files?.[0]||null)} className="text-sm text-slate-400"/><button disabled={busy} onClick={verify} className="rounded-xl bg-cyan-400 px-4 py-2 text-sm font-semibold text-ocean-950 disabled:opacity-50">{busy?"Verifying...":"Request verification"}</button></div><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>status("verified")} className="rounded-xl border border-emerald-400/20 px-3 py-2 text-sm text-emerald-300">Mark verified</button><button onClick={()=>status("rejected")} className="rounded-xl border border-rose-400/20 px-3 py-2 text-sm text-rose-300">Reject</button><span className="rounded-xl border border-white/10 px-3 py-2 text-sm text-slate-400">Status: {d.status}</span></div></section>
  </div>;
}
function Info({label,value,icon:Icon}){return <div className="flex items-start gap-3">{Icon&&<Icon size={17} className="mt-0.5 text-cyan-300"/>}<div><div className="text-xs text-slate-500">{label}</div><div className="mt-1 text-sm text-slate-200">{value}</div></div></div>}