import { useEffect, useState } from "react";
import { getSurveys } from "../services/surveyApi";
import { getJsonReport, downloadCsv, downloadPdf } from "../services/reportApi";
import { downloadBlob } from "../utils/format";
import { FileDown, FileJson, FileSpreadsheet } from "lucide-react";

export default function Reports(){
 const [surveys,setSurveys]=useState([]),[surveyId,setSurveyId]=useState(""),[report,setReport]=useState(null),[error,setError]=useState("");
 useEffect(()=>{getSurveys().then(r=>setSurveys(r.data.data)).catch(e=>setError(e.userMessage||"Could not load surveys"))},[]);
 useEffect(()=>{if(surveyId)getJsonReport(surveyId).then(r=>setReport(r.data.data)).catch(e=>setError(e.userMessage||"Could not load report"))},[surveyId]);
 async function csv(){const r=await downloadCsv(surveyId);downloadBlob(r.data,`${surveyId}.csv`)} async function pdf(){const r=await downloadPdf(surveyId);downloadBlob(r.data,`${surveyId}.pdf`)}
 const ds=report?.detections||[];
 const summary={total:ds.length,ghost:ds.filter(d=>d.classification==="ghost_net").length,shipwreck:ds.filter(d=>d.classification==="shipwreck").length,pipes:ds.filter(d=>d.classification==="pipe").length,critical:ds.filter(d=>d.riskLevel==="CRITICAL").length,area:ds.reduce((s,d)=>s+(d.dimensions?.areaM2||0),0)};
 return <div className="space-y-6"><div><p className="text-sm text-cyan-300">Compliance & exports</p><h1 className="text-3xl font-semibold">Reports</h1><p className="mt-2 text-sm text-slate-500">Generate structured anomaly reports from persisted AI results.</p></div><div className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><select value={surveyId} onChange={e=>setSurveyId(e.target.value)} className="w-full max-w-xl rounded-xl border border-white/10 bg-[#0b202c] px-3 py-3 text-sm"><option value="">Select survey</option>{surveys.map(s=><option key={s.surveyId} value={s.surveyId}>{s.name} — {s.surveyId}</option>)}</select></div>{error&&<div className="rounded-xl border border-rose-400/20 bg-rose-400/10 p-3 text-sm text-rose-300">{error}</div>}{report&&<><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6">{[["Anomalies",summary.total],["Ghost nets",summary.ghost],["Shipwrecks",summary.shipwreck],["Pipes",summary.pipes],["Critical",summary.critical],["Area",`${summary.area.toFixed(1)} m²`]].map(([a,b])=><div key={a} className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><div className="text-xs text-slate-500">{a}</div><div className="mt-2 text-xl font-semibold">{b}</div></div>)}</div><div className="flex flex-wrap gap-2"><button onClick={csv} className="flex items-center gap-2 rounded-xl border border-white/10 px-4 py-2.5 text-sm hover:bg-white/5"><FileSpreadsheet size={16}/>Download CSV</button><button onClick={pdf} className="flex items-center gap-2 rounded-xl border border-white/10 px-4 py-2.5 text-sm hover:bg-white/5"><FileDown size={16}/>Download PDF</button><button onClick={()=>downloadBlob(new Blob([JSON.stringify(report,null,2)],{type:"application/json"}),`${surveyId}.json`)} className="flex items-center gap-2 rounded-xl border border-white/10 px-4 py-2.5 text-sm hover:bg-white/5"><FileJson size={16}/>Download JSON</button></div><div className="overflow-hidden rounded-2xl border border-white/10"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-white/10 text-xs text-slate-500"><tr><th className="px-4 py-3">ID</th><th>Class</th><th>Confidence</th><th>Hazard</th><th>Risk</th><th>Location</th></tr></thead><tbody>{ds.map(d=><tr key={d.detectionId} className="border-b border-white/5"><td className="px-4 py-3">{d.detectionId}</td><td className="capitalize">{d.classification?.replaceAll("_"," ")}</td><td>{d.confidence}%</td><td>{d.hazardScore}</td><td>{d.riskLevel}</td><td>{d.location?.available?`${d.location.latitude}, ${d.location.longitude}`:"Unavailable"}</td></tr>)}</tbody></table></div></div></>}</div>
}